#ci.gocd.yaml
format_version: 9
environments:
  hieu-env:
    environment_variables:
      EXAMPLE_DEPLOYMENT: testing
    pipelines:
    - hieu-test-build-image
pipelines:
  hieu-test-build-image:
    group: hieu-env
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: -1
    materials:
      tops-fe-bitbucket:
        git: https://hieunv3@bitbucket.org/hieunv3/tops-fe.git
    stages:
      - build-image:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: true
          approval:
            type: manual
          jobs:
            list-file: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: ls
                   arguments:
                   - -al
