environments:
  example:
    environment_variables:
      EXAMPLE_DEPLOYMENT: testing
pipelines:
  pipe1:
    group: simple
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/bashman8790/go-docker.git
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              tasks:
               - exec: # indicates type of task
                   command: ls
                   arguments:
                   - -al
