format_version: 4
pipelines:
  yamlpipe1:
    group: simple
    materials:
      mygit:
        plugin_configuration:
          id: GitPathMaterial
          version: 1
        options:
          url: /host
          branch: master
    stages:
      - build: # name of stage
          jobs:
            build: # name of the job
              environment_variables:
                ENV_PASSWORD: secret
              tasks:
               - exec: # indicates type of task
                   command: bash
                   arguments:
                     - -c
                     - "echo $ENV_PASSWORD"
